### PR TITLE
fix: Task and its pinned version not synchronized

### LINKED ISSUE #1245: Task and its pinned version not synchronized
Extension Name: vscode-gradle
Extension Version: v3.12.2
OS Version: Windows
VSCode version: v1.68.1

**Describe the bug**
Task and its pinned version 's running status not synchronized
image

**To Reproduce**
1) In the gradle explorer, pin a task.
2)  Run the task (not its pinned)
3) You see that the task is currently running with the stop button beside it.  But its pinned version does not show that it is currently running

**Expected behavior**
Both the task and its pinned version should show the same running/stopping status.

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1245 

before:

https://user-images.githubusercontent.com/45906942/183561028-464a8deb-11ce-4bc4-9d04-ee53929c7f8c.mp4

after:

https://user-images.githubusercontent.com/45906942/183561064-83fa8e60-0c24-4f1f-b5e5-1c69db350f66.mp4

### CODE REVIEW

**Comment by Eskibear** [comment]
LGTM but when do/will you clear the mapping? (E.g. if I unpin some tasks.)

**Comment by CsCherrYY** [comment]
> LGTM but when do/will you clear the mapping? (E.g. if I unpin some tasks.)

We should clear the map as well in reset function. When you unpin a task, the view is refreshed, and the reset method will also be called.

**Review by Eskibear — APPROVED** [review]

**Comment by CsCherrYY** [comment]
To verify:

1. git clone https://github.com/spring-projects/spring-petclinic
2. open in VS Code and wait for project imported
3. find task "bootRun" in Gradle projects view -> Tasks -> application group
4. right click "bootRun" task and pin it
5. add a breakpoint in main method of `PetClinicApplication` class
6. right click "bootRun" task and choose "debug task", the debug session will stop at the breakpoint
7. check the status of "bootRun" task in both applicaiton group and pinned group, the status are consistent and correct
8. can stop the task from the item in pinned group.

**Comment by Eskibear** [comment]
verified

**Pull request merged**
