### PR TITLE
fix: Store the schema version of the BSP project after import

### PR DESCRIPTION
**Pull request by jdneo**
I didn't find a way to add 'args' to a nature in .project. So use a plugin specific file to store the schema.

### CODE REVIEW

**Comment by jdneo** [comment]
Another two options are:

- Put a comment into the project description file. But since the comment might be replaced by anyone, so this would not be a good choice.
- Put the version as an argument of the Builder, this should work but feels really strange.

**Comment by testforstephen** [comment]
Did you try ProjectDescription.setVariableDescription(...) API, it supports adding more description to the .project file?

**Comment by testforstephen** [comment]
Here is an example:
```
<projectDescription>
...
	<variableList>
		<variable>
			<name>bspSchemaVersion</name>
			<value>0.1.0</value>
		</variable>
	</variableList>
</projectDescription>
```

**Comment by jdneo** [comment]
> Did you try ProjectDescription.setVariableDescription(...) API, it supports adding more description to the .project file?

Looks promising! I was not aware of this, thank you!

**Review by testforstephen — APPROVED** [review]

**Pull request merged**
