### PR TITLE
chore: Use cgmanifest.json to add missed packages

### PR DESCRIPTION
**Pull request by CsCherrYY**
To use Component Governance in this Repo, we will manually add the cgmanifest.json to specify the gradle packages missed by auto detection.

### CODE REVIEW

**Comment by Eskibear** [comment]
Any context information? What happens without adding cgmanifest file?

**Comment by CsCherrYY** [comment]
Currently our Component Detection system in the Azure Devops pipeline can't detect any Gradle components but npm components. Previously we asked CELA for the license suggestions for this repo. In CELA's suggestions, we should make sure all components in Component Governance, so we manually add the missing ones by cgmanifest.json

This json includes all the dependencies from `build.gradle`s in this repo.

**Comment by Eskibear** [comment]
Got it. But here is a problem, we does the list come from? If later we want to introduce some Java dependencies, do we have to also update `cgmanifest.json` manually? 

If it can be easily parsed from all build.gradle files, how about adding a step in pipeline, creating `cgmanifest.json` from build scripts?

**Comment by CsCherrYY** [comment]
> Got it. But here is a problem, we does the list come from? If later we want to introduce some Java dependencies, do we have to also update `cgmanifest.json` manually?
> 
> If it can be easily parsed from all build.gradle files, how about adding a step in pipeline, creating `cgmanifest.json` from build scripts?

Good suggestion, let's use https://github.com/microsoft/vscode-gradle/issues/1083 to track this engineering item.

**Review by Eskibear — APPROVED** [review]

**Pull request merged**
