### PR TITLE
Gradle project view keeps project hierarchy

### PR DESCRIPTION
**Pull request by jjohannes**
Implements #945 by parsing the project path which is found in the `definition.script` property. The project path, which is unique for every subproject, is then used as key in the `projectTreeItemMap`.

### CODE REVIEW

**Comment by jjohannes** [comment]
@microsoft-github-policy-service agree

**Comment by jdneo** [comment]
Thank you @jjohannes.

I'm just back from vacation and will review this contribution ASAP.

**Review by jdneo — APPROVED** [review]

**Comment by jjohannes** [comment]
Thank you for the quick response and integrating this @jdneo.

**Comment by jdneo** [comment]
I found an issue about this change that some of the modules are in the wrong place:

image

For example, here: the `app` and `mylibrary` should belong to `android-test`.

Clone and open the project https://github.com/microsoft/build-server-for-gradle can reproduce the error

**Pull request merged**
