### PR TITLE
Changes for hierarchical tree structure of sub-projects

### LINKED ISSUE #945: Gradle Project view should keep project hierarchy
Currently our Project view is a flat view, for some hierarchical projects it might not be intuitive to the users, and it can't provide relationships among projects.

So we should support hierarchy view of projects, and offer a way to switch between the two views.

### PR DESCRIPTION
**Pull request by uiv24008**
Changes for hierarchical tree structure of sub-projects. Fix #945

### CODE REVIEW

**Comment by jdneo** [comment]
Hi @uiv24008

There are some CLA check that you need to do as a follow-up, please check https://github.com/microsoft/vscode-gradle/pull/1592#issuecomment-2312014574.

~Meanwhile, I think it would be good if we can introduce a setting to control whether the tree view should be displayed hierarchical or flat.~

**Comment by jdneo** [comment]
Took a look at IDEA and it's hierarchical by default and seems not able to switch to flat. So adding the setting to control the view style is not required.

**Comment by jdneo** [comment]
One feedback is about the place of the `Tasks` and `Dependencies` node of the parent project.

You can see that they are now placed at the bottom of the children nodes, which mixes with the above child project

image

I suggest to put it at the top of the child list. This is also how IDEA display:

image

**Comment by uiv24008** [comment]
Hi @jdneo,

I have modified the code and able to see **Tasks** and **Dependencies** node of the parent project as below:

image

Please let me know if it is fine, I will push the code changes

**Comment by jdneo** [comment]
Yes this is what I mean. Thank you!

**Comment by jdneo** [comment]
And don't forget this: https://github.com/microsoft/vscode-gradle/pull/1592#issuecomment-2312014574

**Comment by jdneo** [comment]
Hi,

There are some lint errors. I think you can run the format task to fix them

image

After running the task you can rerun `:extension:lint` to check if it can pass

**Comment by uiv24008** [comment]
> Hi,
> 
> There are some lint errors. I think you can run the format task to fix them
> 
> image
> 
> After running the task you can rerun `:extension:lint` to check if it can pass

Hi @jdneo , can you please mention the steps to reproduce the issue? I am not able to see "**format**" option under tasks

image

**Comment by jdneo** [comment]
@uiv24008 It is in the vscode-gradle, not the project you are testing with.

The repo has some restrictions on the code formatting, the task I mentioned are used to check and correct the code format.

**Review by jdneo — APPROVED** [review]
LGTM

**Comment by uiv24008** [comment]
I am trying to create .vsix file by running the command "vsce package", not able to create .vsix file and getting below error

image

Node version: v14.21.3

**Comment by jdneo** [comment]
@uiv24008 Could you `cd` to `extension` folder and try again?


If it's still not working, please try updating node to 18

**Comment by jdneo** [comment]
Hi @uiv24008, would you mind me closing this PR since we have https://github.com/microsoft/vscode-gradle/pull/1612 for this?

**Comment by uiv24008** [comment]
Hi @Sheng ***@***.***>

Yes, you can close the PR #1592. It is not required

Thanks & Regards,
Shilpa S Patil

**Pull request closed without merging**
